# (remove top-level version key—Compose v2 ignores it)

services:
  elasticsearch:
    image: docker.io/library/elasticsearch:8.18.0
    container_name: es-local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:                     # <─── NEW
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
      interval: 10s
      timeout: 5s
      retries: 20                    # ≈ 200 s max

  api:
    build: .
    container_name: multilingual-doc-api
    env_file:
      - .env
    depends_on:                      # <─── UPDATED
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  es_data:
