version: "3.8"

services:
  # ---------- 1) Elasticsearch (single node, dev profile) ----------
  elasticsearch:
    image: docker.io/library/elasticsearch:8.18.0
    container_name: es-local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false           # disable security for local dev
      - ES_JAVA_OPTS=-Xms1g -Xmx1g             # 1 GB heap (tune per machine)
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # ---------- 2) FastAPI application ----------
  api:
    build: .
    container_name: multilingual-doc-api
    env_file:
      - .env
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload    

volumes:
  es_data:
